// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tcc_core.Data;

#nullable disable

namespace tcc_core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240917004148_AddIsActiveUsuario")]
    partial class AddIsActiveUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("tcc_core.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DtFinal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DtInicial")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Feedback")
                        .HasColumnType("longtext");

                    b.Property<bool>("HasProjeto")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<int?>("ProjetoId")
                        .HasColumnType("int");

                    b.Property<int>("QtdPessoas")
                        .HasColumnType("int");

                    b.Property<string>("ResponsavelExterno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsavelInterno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Turma")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Agendamento");
                });

            modelBuilder.Entity("tcc_core.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Classificacao")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("QuantidadeAtual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("tcc_core.Models.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DtMovimentacao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HasProjeto")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ProjetoId")
                        .HasColumnType("int");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoMovimentacao")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Movimentacao");
                });

            modelBuilder.Entity("tcc_core.Models.MovimentacaoMaterial", b =>
                {
                    b.Property<int>("MovimentacaoId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MovimentacaoId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("MovimentacaoMaterial");
                });

            modelBuilder.Entity("tcc_core.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Coordenador")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DtFinal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DtInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Natureza")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Projeto");
                });

            modelBuilder.Entity("tcc_core.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("tcc_core.Models.Agendamento", b =>
                {
                    b.HasOne("tcc_core.Models.Projeto", "Projeto")
                        .WithMany("Agendamento")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tcc_core.Models.Usuario", "Usuario")
                        .WithMany("Agendamento")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Projeto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("tcc_core.Models.Movimentacao", b =>
                {
                    b.HasOne("tcc_core.Models.Projeto", "Projeto")
                        .WithMany("Movimentacao")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tcc_core.Models.Usuario", "Usuario")
                        .WithMany("Movimentacao")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Projeto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("tcc_core.Models.MovimentacaoMaterial", b =>
                {
                    b.HasOne("tcc_core.Models.Material", "Material")
                        .WithMany("MovimentacaoMaterial")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tcc_core.Models.Movimentacao", "Movimentacao")
                        .WithMany("MovimentacaoMaterial")
                        .HasForeignKey("MovimentacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Movimentacao");
                });

            modelBuilder.Entity("tcc_core.Models.Material", b =>
                {
                    b.Navigation("MovimentacaoMaterial");
                });

            modelBuilder.Entity("tcc_core.Models.Movimentacao", b =>
                {
                    b.Navigation("MovimentacaoMaterial");
                });

            modelBuilder.Entity("tcc_core.Models.Projeto", b =>
                {
                    b.Navigation("Agendamento");

                    b.Navigation("Movimentacao");
                });

            modelBuilder.Entity("tcc_core.Models.Usuario", b =>
                {
                    b.Navigation("Agendamento");

                    b.Navigation("Movimentacao");
                });
#pragma warning restore 612, 618
        }
    }
}
