// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tcc_core.Data;

#nullable disable

namespace tcc_core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240504175528_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("tcc_core.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DtFinal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DtInicial")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ProjetoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("QtdPessoas")
                        .HasColumnType("int");

                    b.Property<string>("ResponsavelExterno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsavelInterno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Turma")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Agendamento");
                });

            modelBuilder.Entity("tcc_core.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("QuantidadeAtual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("tcc_core.Models.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DtMovimentacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ProjetoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Responsavelonsavel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoMovimentacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Movimentacao");
                });

            modelBuilder.Entity("tcc_core.Models.MovimentacaoMaterial", b =>
                {
                    b.Property<int>("MovimentacaoId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MovimentacaoId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("MovimentacaoMaterial");
                });

            modelBuilder.Entity("tcc_core.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Coordenador")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DtFinal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DtInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Natureza")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Projeto");
                });

            modelBuilder.Entity("tcc_core.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("tcc_core.Models.Agendamento", b =>
                {
                    b.HasOne("tcc_core.Models.Projeto", "Projeto")
                        .WithMany("Agendamento")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tcc_core.Models.Usuario", "Usuario")
                        .WithMany("Agendamento")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("tcc_core.Models.Movimentacao", b =>
                {
                    b.HasOne("tcc_core.Models.Projeto", "Projeto")
                        .WithMany("Movimentacao")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tcc_core.Models.Usuario", "Usuario")
                        .WithMany("Movimentacao")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("tcc_core.Models.MovimentacaoMaterial", b =>
                {
                    b.HasOne("tcc_core.Models.Material", "Material")
                        .WithMany("MovimentacaoMaterial")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tcc_core.Models.Movimentacao", "Movimentacao")
                        .WithMany("MovimentacaoMaterial")
                        .HasForeignKey("MovimentacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Movimentacao");
                });

            modelBuilder.Entity("tcc_core.Models.Material", b =>
                {
                    b.Navigation("MovimentacaoMaterial");
                });

            modelBuilder.Entity("tcc_core.Models.Movimentacao", b =>
                {
                    b.Navigation("MovimentacaoMaterial");
                });

            modelBuilder.Entity("tcc_core.Models.Projeto", b =>
                {
                    b.Navigation("Agendamento");

                    b.Navigation("Movimentacao");
                });

            modelBuilder.Entity("tcc_core.Models.Usuario", b =>
                {
                    b.Navigation("Agendamento");

                    b.Navigation("Movimentacao");
                });
#pragma warning restore 612, 618
        }
    }
}
